### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.26.3


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [2]:
# Начало вашего кода
numbers = np.array([[i for i in range(0, 10, 2)],
                   [i for i in range(1, 11, 2)]])
# Конец вашего кода
print(numbers)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [3]:
# Начало вашего кода
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)
print(numbers.T)

# Конец вашего кода

2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [4]:
# Начало вашего кода
overall_max = numbers.max()
overall_min = numbers.min()
overall_mean = numbers.mean()
overall_std = numbers.std()
# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [5]:
# Начало вашего кода
col_max = numbers.max(axis=0, keepdims=True)
col_min = numbers.min(axis=0, keepdims=True)
col_mean = numbers.mean(axis=0, keepdims=True)
col_std = numbers.std(axis=0, keepdims=True)
# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [6]:
# Начало вашего кода
row_max = numbers.max(axis=1, keepdims=True)
row_min = numbers.min(axis=1, keepdims=True)
row_mean = numbers.mean(axis=1, keepdims=True)
row_std = numbers.std(axis=1, keepdims=True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [7]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [8]:
# Начало вашего кода
print('Mean with respect to 0-axis')
print(thd_nparr.mean(axis=0, keepdims=True))
print('STD with respect to 0-axis')
print(thd_nparr.std(axis=0, keepdims=True))
print('\n')
print('Mean with respect to 1-axis')
print(thd_nparr.mean(axis=1, keepdims=True))
print('STD with respect to 1-axis')
print(thd_nparr.std(axis=1, keepdims=True))
print('\n')
print('Mean with respect to 2-axis')
print(thd_nparr.mean(axis=2, keepdims=True))
print('STD with respect to 2-axis')
print(thd_nparr.std(axis=2, keepdims=True))
# Конец вашего кода

Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [9]:
# ndarray.reshape()
# Начало вашего кода
n = thd_nparr.reshape(2,2,2)
print(n)
# Конец вашего кода

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


In [10]:
# ndarray.ravel()
# Начало вашего кода
n.ravel(order='F')
# Конец вашего кода

array([ 1, 21,  3, 23,  2, 22,  4, 24])

In [11]:
# ndarray.tolist()
# Начало вашего кода
print(thd_nparr.tolist()) # преобразовывает hdarray в обычный массив питона
# Конец вашего кода

[[[1, 2], [3, 4]], [[21, 22], [23, 24]]]


In [12]:
# ndarray.tofile()
# Начало вашего кода
my_array = np.array([[6, 4, 1], [2, 5, 3]])
with open('array.txt', 'w') as file: 
    my_array.tofile(file) # запись данных в бинарной форме
# Конец вашего кода

In [13]:
# ndarray.sort()
# Начало вашего кода
new_arrya = my_array.copy()
new_arrya.sort(axis=1)
print(new_arrya)
# Конец вашего кода

[[1 4 6]
 [2 3 5]]


In [14]:
# ndarray.transpose()
# Начало вашего кода
transpose_array = my_array.transpose()
print(transpose_array)
# Конец вашего кода

[[6 2]
 [4 5]
 [1 3]]


In [15]:
# ndarray.flatten()
# Начало вашего кода
flatten_array = transpose_array.flatten()
print(flatten_array)
# Конец вашего кода

[6 2 4 5 1 3]


In [20]:
# ndarray.argmin()
# Начало вашего кода
argmin_array = flatten_array.argmin()
print(argmin_array)
# Конец вашего кода

4


In [23]:
# ndarray.argmax()
# Начало вашего кода
argmax_array = flatten_array.argmax()
print(argmax_array)
# Конец вашего кода

0


In [24]:
# ndarray.cumsum()
# Начало вашего кода
cumsum_array = flatten_array.cumsum()
print(cumsum_array)
# Конец вашего кода

[ 6  8 12 17 18 21]


In [26]:
# ndarray.cumprod()
# Начало вашего кода
cumprod_array = flatten_array.cumprod()
print(cumprod_array)
# Конец вашего кода

[  6  12  48 240 240 720]


In [30]:
# ndarray.dot()
# Начало вашего кода
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_array = np.dot(matrix1, matrix2)
print(dot_array)
# Конец вашего кода

[[19 22]
 [43 50]]


In [39]:
# ndarray.squeeze()
# Начало вашего кода
matrix3 = np.array([[[1]],[[2]],[[3]]])
squeeze_array = np.squeeze(matrix3)

print(matrix3)
print(matrix3.shape)
print(squeeze_array)
print(squeeze_array.shape)
# Конец вашего кода

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)
[1 2 3]
(3,)


In [40]:
# ndarray.repeat()
# Начало вашего кода
repeat_array = np.repeat(squeeze_array, 3)
print(repeat_array)
# Конец вашего кода

[1 1 1 2 2 2 3 3 3]


# Прекрасная работа!