### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [5]:
import numpy as np
import numpy.random as rd

In [6]:
# numpy.zeros
arr1 = np.zeros((3,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# numpy.ones
arr2 = np.ones((3,5))
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# numpy.full
arr3 = np.full((3,5), 13)
print(arr3)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [14]:
# numpy.eye
arr4 = np.eye(8)
print(arr4)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
# numpy.arange
arr5 = np.arange(1000, 0, -7)
print(arr5)

[1000  993  986  979  972  965  958  951  944  937  930  923  916  909
  902  895  888  881  874  867  860  853  846  839  832  825  818  811
  804  797  790  783  776  769  762  755  748  741  734  727  720  713
  706  699  692  685  678  671  664  657  650  643  636  629  622  615
  608  601  594  587  580  573  566  559  552  545  538  531  524  517
  510  503  496  489  482  475  468  461  454  447  440  433  426  419
  412  405  398  391  384  377  370  363  356  349  342  335  328  321
  314  307  300  293  286  279  272  265  258  251  244  237  230  223
  216  209  202  195  188  181  174  167  160  153  146  139  132  125
  118  111  104   97   90   83   76   69   62   55   48   41   34   27
   20   13    6]


In [19]:
# numpy.add
ndarray1 = np.array([1,2,3,4])
ndarray2 = np.array([5,6,7,8])
ndarray3 = np.add(ndarray1, ndarray2)
print(ndarray3)


[ 6  8 10 12]


In [20]:
# numpy.subtract
ndarray3 = np.subtract(ndarray1, ndarray2)
print(ndarray3)

[-4 -4 -4 -4]


In [22]:
# numpy.sin
ndarray4 = np.sin(ndarray1)
print(ndarray4)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [24]:
# numpy.multiply
ndarray5 = np.multiply(ndarray1, ndarray2)
print(ndarray5)

[ 5 12 21 32]


In [26]:
# numpy.sqrt
ndarray6 = np.sqrt(ndarray5)
print(ndarray6)

[2.23606798 3.46410162 4.58257569 5.65685425]


In [37]:
# numpy.dot
dot_arr1 = np.array([[1,2,3],[4,5,6]])
dot_arr2 = np.array([[7],[8],[9]])
dot_arr3 = np.dot(dot_arr1, dot_arr2)
print(dot_arr3)

[[ 50]
 [122]]


In [40]:
# numpy.sum
sum__arr1 = np.array([[1,2],[3,4]])
sum__arr2 = np.array([[5,6],[7,8]])
sum__arr3 = np.add(sum__arr1, sum__arr2)
print(sum__arr3)

[[ 6  8]
 [10 12]]


In [49]:
# numpy.zeros_like
a = np.arange(12)
b = a.reshape((4,3))
c = np.zeros_like(b)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
# numpy.empty_like
a = np.arange(12)
b = a.reshape((4,3))
c = np.empty_like(b)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [65]:
# numpy.reshape
a = np.arange(8)
b = a.reshape((4,2))
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [67]:
# numpy.isnan
array = np.array([np.NaN, 34, 76, 55, np.NaN, np.NaN])
print(np.isnan(array))

[ True False False False  True  True]


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [68]:
# numpy.random.sample
rd.sample()

0.32547206401943174

In [72]:
# numpy.random.random
rd_array = rd.random((3,4))

print(rd_array)

[[0.90967635 0.8544393  0.34888004 0.3439327 ]
 [0.35585652 0.38817653 0.35106229 0.46551849]
 [0.5426955  0.43342911 0.2599653  0.67216748]]


In [75]:
# numpy.random.randint
rd_array = rd.randint(1,8 + 1,(3,4))
print(rd_array)

[[5 2 3 8]
 [8 7 4 8]
 [8 8 2 6]]


In [76]:
# numpy.random.random_integers
rd_array = rd.random_integers(1,8,(3,4))
print(rd_array)

[[3 2 8 6]
 [5 5 3 5]
 [6 6 7 3]]


/tmp/ipykernel_57956/4275734462.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 8 + 1) instead
  rd_array = rd.random_integers(1,8,(3,4))


In [83]:
# numpy.random.uniform
# в этом случае будет печатать числа в кол-ве аргументов и в промежутке самого аргумента
rd.uniform((3, 4))
rd.uniform(2,4,size=(3, 4)) # в этом случае передается промежуток рандома и после размер массива

array([[2.21169356, 2.92506637, 2.58891791, 2.50985743],
       [2.28924598, 3.04740423, 2.59413776, 2.21707386],
       [2.84561908, 3.43541244, 2.61365751, 2.95543222]])

In [152]:
# numpy.random.seed
rd.seed(1) # точка сохранения

In [153]:
# numpy.random.shuffle
fruit_list = ['banana','apple','mondarino','orange']
rd.shuffle(fruit_list) # также перестановка
print(fruit_list)


['orange', 'mondarino', 'banana', 'apple']


In [154]:
# numpy.random.permutation
my_arr = rd.randint(1,9,(5))
print(my_arr)
new_arr = rd.permutation(my_arr) # перестановка
print(new_arr)


[8 2 4 6 8]
[4 6 2 8 8]


In [155]:
# numpy.random.choice
print(rd.choice(6, (2,3)))

[[5 4 1]
 [2 4 5]]


# Прекрасная работа!