### NumPy: Индексы & Срезы [Домашнее задание]

> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.26.3


### Ожидаемый результат
```
1.17.4
```

2. Вам предоставляется список ```list1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]```.
Пожалуйста, извлеките элементы списка ```list1```, который разделяет его индекс в списке ```list1``` без остатка. Используйте два подхода для решения этой проблемы, используя только список ```list``` и используя массив ```numpy.ndarray``` отдельно.

    **Примечание: не используйте ```enumerate```.**

In [3]:
list1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]
list2 = []

# list
# Начало вашего кода
for i in range(len(list1)):
    if i % list1[i] == 0:
        list2.append(list1[i])
# Конец вашего кода
print(list2)

[1, 5, 2]


### Ожидаемый результат
```
[1, 5, 2]
```

In [9]:
# numpy.ndarray
# Начало вашего кода
ndarr1 = np.array(list1)
list3 = []
for i in range(len(ndarr1)):
    if i % ndarr1[i] == 0:
        list3.append(ndarr1[i])
        
ndarr2 = np.array(list3)
# Конец вашего кода
print(ndarr2)

[1 5 2]


### Ожидаемый результат
```
[1 5 2]
```

3. Вам предоставляется список списков ```list_of_lists=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]```. Пожалуйста, извлеките элементы, которые делят произведение индекса строки и индекса столбца без остатка.Используйте два подхода для решения этой проблемы, используя только список list и используя массив numpy.ndarray отдельно.

**Примечание: не используйте ```enumerate```.**

In [10]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
new_list = []

# list
# Начало вашего кода
for i in range(len(list_of_lists)):
    for j in range(len(list_of_lists[i])):
        if (i * j) % list_of_lists[i][j] == 0:
            new_list.append(list_of_lists[i][j])
# Конец вашего кода
print(new_list)

[1, 2, 3, 4, 5, 9]


### Ожидаемый результат
```
[1, 2, 3, 4, 5, 9]
```

In [15]:
# numpy.ndarray
# Начало вашего кода
array_fo_lists = np.array(list_of_lists)
new_array = []
for i in range(len(array_fo_lists)):
    for j in range(len(array_fo_lists[i])):
        if (i * j) % array_fo_lists[i][j] == 0:
            new_array.append(array_fo_lists[i][j])
            
ndarr3 = np.array(new_array)
# Конец вашего кода
print(ndarr3)

[1 2 3 4 5 9]


### Ожидаемый результат
```
[1 2 3 4 5 9]
```

4. Пожалуйста, напишите две функции:

```slice_list(orig_list, row_str, row_end, col_str, col_end)```

```slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end)```


row_str и row_end - начальный индекс столбца и конечный индекс столбца среза.

col_str и col_end - начальный индекс столбца и конечный индекс столбца среза.

Пример:
```
orig_list =[[ 1, 2, 3],
            [11,12,13],
            [21,22,23]]

res_list = slice_list(orig_list, 0, 2, 1, 3)

Ответ:
res_list = [[ 2, 3],
            [12,13]]

```

In [23]:
list_of_lists = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16],
                 [17,18,19,20]]

def slice_list(orig_list, row_str, row_end, col_str, col_end):
    # list
    # Начало вашего кода
    res_list = []
    for i in range(row_str, row_end):
        sliced_row = []
        for j in range(col_str, col_end):
            sliced_row.append(orig_list[i][j])
        res_list.append(sliced_row)
    return res_list
    # Конец вашего кода

print(slice_list(list_of_lists,1,4,1,3))

[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

In [27]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

def slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end):
    # numpy.ndarray
    # Начало вашего кода
    nums_array = np.array(list_of_lists)
    res_array = nums_array[row_str:row_end, col_str:col_end].tolist()
    return res_array
    # Конец вашего кода

print(slice_list_ndarr(list_of_lists,1,4,1,3))

[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

# Прекрасная работа!